### ISSUE TITLE
Doesn't work for me.

### ISSUE THREAD

**Issue by fourjr** [PotcFdk/DiscordGameStatus#7]
Am online, set playing game to `alone` and it didnt work.

**Comment by PotcFdk** [comment]
Please supply the following information:
- browser
- Greasemonkey or Tampermonkey?
- Is the DiscordGameStatus userscript up-to-date? (should be v1.4.0)
- Does the infobubble, that appears when you hover/mouseover the button, show `alone`?
- How have you determined that it didn't work?

**Comment by fourjr** [comment]
Google Chrome.
Tampermonkey.
I just installed it before my pull request.
Yes.
I switched to online and looked at sidebar.

**Comment by PotcFdk** [comment]
>I switched to online and looked at sidebar.

You can't see your own status. Check from another account or ask a friend if the status is set correctly.  
If that is not showing your status either, please comment on this issue again to re-open it.

As far as I can tell, this is a limitation of the Discord protocol. The API doesn't fully notify you about your own status, so the web app doesn't show it either. As a workaround, when you mouseover/hover the button, it shows your game status. This is not a proof that it, in fact, has been registered by the Discord servers, but should reflect the clientside view of things, at the very least.

(Technical details:  
When sending a message with `op=3` (aka the status update request), and the `d.status` field differs from your current online state (e.g. changed from `online` to `idle`) you receive back a `USER_SETTINGS_UPDATE` that contains a `d.status` with the new status. That's why the online status (the green/yellow/red circle next to your avatar in the sidebar) is updated - the web app listens for that message and updates the sidebar accordingly. However, the game name is not reflected this way, so the web app is not notified about the game status. As far as I can tell, the only way to make this work is to handle this manually, which seems very complex at this time, because all of the ways to make (and keep it) it showing the correct details are complex and troublesome.)
